30 choose signal types to receive notifications
HelpAPaw/Android pull request #31
Opened 2021-02-23 20:13 UTC by medeaohm

2021-03-26 11:58 UTC, BurningAXE requested changes

2021-03-26 11:58 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +                        int signalTypes = Integer.parseInt(device.get("signalTypes").toString());
signalTypes е Int, защо го конвертираме в стринг и обратно в Int?

2021-03-26 11:58 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +                        if ((signalTypes & (1 << shift)) > 0) {
Тук не разбирам логиката. Ако сигналът е с тип 6, се получава shift = 0!?
Според мен трябва да е:
```
int shift = (int) Math.pow(2, signal.getType());
                        
if ((signalTypes & (1 << shift)) > 0) {
    notifiedDevices.add(device.get("deviceId").toString());
}
```

2021-03-26 11:58 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +        return MAX_PADDING | signalTypes;
Това може да създаде проблем ако добавим нови типове и забравим да го променим. По-универсално ще е:
`(65535 << SIGNAL_TYPES_SIZE) | signalTypes;`

2021-03-27 15:12 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/SettingsRepository.java
> +        return preferences.getInt(SIGNAL_TYPES_FIELD, 127);
changed to preferences.getInt(SIGNAL_TYPES_FIELD, 65535);

2021-03-27 15:15 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/SettingsFragment.java
> +                intent.putExtra("selected_types",
ok

2021-03-27 15:19 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/SignalTypeSettingsActivity.java
> +    private static final int REQUEST_CHANGE_SIGNAL_TYPES = 1;
Оставям го само тук и ще го викам от SettingsRepository

2021-03-27 15:22 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +    public void pushNewSignalNotification(final Signal signal, final double latitude, final double longitude, final int signalType) {
да, махам го

2021-03-27 15:24 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +    public void pushNewSignalNotification(final Signal signal, final double latitude, final double longitude, final int signalType) {
Да го оправя ли аз като част от този ПР? Ще ги взимам като signal.getLatitude() и signal.getLongitude() и ще оправя сигнатурата на метода.

2021-03-27 15:30 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +    public void pushNewSignalNotification(final Signal signal, final double latitude, final double longitude, final int signalType) {
Да, то така или иначе от там се взима.

2021-03-27 15:48 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/SignalTypeCustomAdapter.java
> +    public int getViewTypeCount() {
Този метод не се ползва никъде. Оправям го все пак, да си е правилен :)

2021-03-27 15:49 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/SignalTypeCustomAdapter.java
> +    public int getItemViewType(int position) {
Този метод не се ползва никъде. Оправям го все пак, да си е правилен :)

2021-03-27 15:50 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/SignalTypeCustomAdapter.java
> +        return 0;
Този метод не се ползва никъде. Оправям го все пак, да си е правилен :)

2021-03-27 15:56 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +                        int signalTypes = Integer.parseInt(device.get("signalTypes").toString());
done

2021-03-27 16:19 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +                        if ((signalTypes & (1 << shift)) > 0) {
Mисля, че това няма да сработи, понеже битовете са наредени на "обратно". Тоест, ако дадено устройство е избрало да получава нотификации само за signalType 6, тогава неговият SignalTypes ще бъде 65409 (=1111 1111 1000 0001). Tочно за това мисля, че трябва да вземем първия бит (1 << 0 = 1) В противен случай ще имаме shift = 64 (0100 0000) и реално няма да правим правилната проверка.

2021-03-27 16:36 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +        return MAX_PADDING | signalTypes;
He съм сигурна, че разбирам защо трябва да е така?
Да вземем например:
signalTypes = 1 (което би означавало, че device-a ще получава нотификации само за signalType = 6)
MAX_PADDING =  65408 (=1111 1111 1000 0000)
SIGNAL_TYPES_SIZE = 7

Тогава бихме получили: 
MAX_PADDING | signalTypes = 65409 (=1111 1111 1000 0001)
(65535 << SIGNAL_TYPES_SIZE) | signalTypes = 8388481 (=111 1111 1111 1111 1000 0001) тоест по този начин ще имаме доста повече от 16 бита

2021-03-27 16:51 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/SettingsFragment.java
> +                        Utils.convertIntegerToBooleanArray(selectedTypesForDb, signalTypes.length));
Не съм сигурна, че разбирам какво имаш предвид. В базата имаме Int който в някакъв момент трябва да конвертираме към boolean[] за да го презентираме в checkbox-ите и обратното...

2021-03-27 16:59 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/SignalTypeSettingsActivity.java
> +        customAdapter.setSignalTypeSelectionToCurrent();
В адаптора имаме signalTypeSelection и currentSignalTypeSelection, като signalTypeSelection  е каквото е запазено, докато currentSignalTypeSelection е текущото състояние на checkbox-ите. Когато искаме да запазим текущата селекция, сетваме в адаптера signalTypeSelection да е равно на currentSignalTypeSelection.

2021-03-27 17:08 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/SignalTypeCustomAdapter.java
> +        System.arraycopy(currentSignalTypeSelection, 0, signalTypeSelection, 0, signalTypeSelection.length);
Целта на този метод не е да връща current selection, a по-скоро да сетва signalTypeSelection да е current selection (той е нужен, защото не винаги искаме да го "запазваме"). Moже user-a в един момент да се откаже от current selection (тук при нотификациите не защото идеяда е да се запазва когато излезе от екранта, но при филтрирането например е възможно user-a да не запази филтъра)

2021-03-27 22:28 UTC, medeaohm commented on app/src/main/res/layout/activity_signal_type_settings.xml
> +            <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
да, може да се махне

2021-03-27 22:48 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/SettingsFragment.java
> +    public View.OnClickListener onSelectedSignalTypeChangeListener() {
ok, преименувам го

2021-03-27 22:52 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/SignalTypeSettingsActivity.java
> +        startActivityForResult(resultIntent, 90);
Тук ако извикам направо finish() не се връщам на settings екрана...

2021-03-27 23:09 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/SignalTypeSettingsActivity.java
> +    public void onBackPressed() {
Не съм сигурна защо, но когато ползвам onDestroy() се полуачава едно премигване на екрана.Да го обсъдим на следващата среща?

2021-04-01 15:13 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +        return MAX_PADDING | signalTypes;
Евентуално вярно:
`((65535 << SIGNAL_TYPES_SIZE) & 65535) | signalTypes;`

2021-04-01 16:20 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +        return MAX_PADDING | signalTypes;
done

2021-04-01 16:21 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +                        if ((signalTypes & (1 << shift)) > 0) {
След последните промени с "обръщането" на битовете, е достатъчно:
int shift = signal.getType();

2021-04-05 09:21 UTC, BurningAXE commented
- [ ] Background check shows notifications for all signal types regardless of notification settings
- [ ] Background check shows notifications for signals for which a push notification was received

2021-04-05 13:12 UTC, BurningAXE approved these changes

2021-04-05 13:12 UTC, merged