38-avoiding-iob-exception-when-adding-new-signal-type
HelpAPaw/Android pull request #39
Opened 2021-04-14 21:36 UTC by medeaohm

2021-04-15 09:56 UTC, BurningAXE requested changes

2021-04-15 09:56 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                    if (selectedTypes != null && !selectedTypes[presentSignal.getType()]) {
Ако selectedTypes може да е null, това трябва да е първата проверка, иначе ще гръмне преди нея.
Може двата иф-а направо да се обединят:
`if ((selectedTypes != null) && 
                    (selectedTypes.length > presentSignal.getType()) &&
                    !selectedTypes[presentSignal.getType()]) {
                    signalToRemove = presentSignal;
                    break;
                }`

2021-04-15 13:55 UTC, BurningAXE commented
Докато ръчкам iOS-a открих още един бъг:
- Потребител ползва приложението и си е запазил някакви настройки (дори и да са всички сигнали избрани)
- Добавяме нов тип в приложението
- Потребителя си инсталира ъпдейта
=> Показва му новия тип като деселектиран, докато в бекенда е записан като селектиран (понеже правим падинг с единици)
Т.е. трябва да правим същото нещо с падинга и в локалните настройки и като цяло да пазим същото нещо от бекенда.
Може да го отделим това в отделно issue или направо с това.

2021-04-27 21:23 UTC, medeaohm commented
Направих го като част от този ПР. Ще изтествам всичко и после сме готови за merge

2021-05-05 13:11 UTC, BurningAXE requested changes

2021-05-05 13:11 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                if (selectedTypes != null && !selectedTypes[presentSignal.getType()] &&
Проверката за големината май трябва да е на второ място!? Иначе ще крашне при опита да достъпи елемента извън границите преди да е проверило големината. Т.е.:
`if ((selectedTypes != null) &&
                         (selectedTypes.length > presentSignal.getType()) && !selectedTypes[presentSignal.getType()])`

2021-05-06 22:33 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                if (selectedTypes != null && !selectedTypes[presentSignal.getType()] &&
Да, така е. Между другото докато го гледах се натъкнах на още един corner case. Да речем, че имаме в базата сигнал с тип 7, а във версията на user-a максимума е 6. Тогава имаме малък проблем когато се опитваме да филтрираме. Какво ще кажеш да направим:

                if ((selectedTypes != null) && !(Utils.allSelected(selectedTypes)) &&
                        (selectedTypes.length > presentSignal.getType()) &&
                        (!selectedTypes[presentSignal.getType()] || presentSignal.getType() >= selectedTypes.length )) {
                    signalToRemove = presentSignal;
                    break;
                }
if-a не е много четим, но поне бихме имали следното поведение:
- Ако при филтриране са селектирани всички типове, тогава user-a ще вижда всички сигнали, включително и този с тип 7
- Ако има някакъв филтъп, тогава и тип 7 ще бъде изключвам

2021-05-07 07:20 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                if (selectedTypes != null && !selectedTypes[presentSignal.getType()] &&
Честно казано, да не крашва при неъпдейтнатите ми се струва достатъчно. Така че в случая по-скоро бих предпочел по-ясен код, но нямам силни чувства по въпроса. Само ако го оставиш така му добави един коментар кое защо е, за да не го мъдрим след някой друг месец :)

2021-05-07 18:34 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                if (selectedTypes != null && !selectedTypes[presentSignal.getType()] &&
Както се разбрахме, махнах допълнителните чекове.

2021-05-10 08:32 UTC, BurningAXE approved these changes

2021-05-10 08:32 UTC, merged