41 - Fix NPE in SignalTypeCustomAdapter
HelpAPaw/Android pull request #42
Opened 2021-05-27 18:16 UTC by medeaohm

Fixes #41

2021-05-28 16:19 UTC, BurningAXE requested changes
Тествах го при мен и изглежда, че работи. Само една малка забележка за стринговете, за да не стават грешки.

2021-05-28 16:19 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/FilterSignalTypeDialog.java
> +            signalTypeSelection = savedInstanceState.getBooleanArray("signalTypeSelection");
Нека да изнесем стринговете в макроси

2021-05-28 16:19 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/FilterSignalTypeDialog.java
> +        if (tag != null && tag.equals("filter")) {
Този също

2021-05-29 09:50 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/FilterSignalTypeDialog.java
> +            signalTypeSelection = savedInstanceState.getBooleanArray("signalTypeSelection");
done

2021-05-29 09:50 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/FilterSignalTypeDialog.java
> +        if (tag != null && tag.equals("filter")) {
done

2021-05-30 07:08 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/FilterSignalTypeDialog.java
> +        if (tag != null && tag.equals("filter")) {
Тук имах предвид "filter" тага, понеже го има на 2 места, но май не е променен!?

2021-05-30 08:07 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/filtersignal/FilterSignalTypeDialog.java
> +        if (tag != null && tag.equals("filter")) {
да, сори, не бях разбрала че за него става въпрос. Oправих го

2021-05-30 08:59 UTC, BurningAXE approved these changes

2021-05-30 08:59 UTC, merged