40 possibility to upload photo after signal creation
HelpAPaw/Android pull request #43
Opened 2021-06-02 18:46 UTC by medeaohm

2021-06-03 15:09 UTC, BurningAXE requested changes

2021-06-03 15:09 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
>  public interface SignalPhotoContract {
Този интерфейс е SignalPhotoFragment, който показва снимката на цял екран. Той няма общо с качването на снимка, така че новите методи по-скоро трябва да са в отделен интерфейс от сорта UploadPhotoContract

2021-06-03 15:09 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
> +                                              FragmentManager fragmentManager) {
Реално имплементиращите интерфейса ще бъдат фрагменти, така че няма нужда да им пращаме fragmentManager. Достатъчно е да се декларира метод FragmentManager getFragmentManager() в интерфейса и да се ползва той в метода вместо аргумента.

2021-06-03 15:09 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
> +        default void openGallery(Fragment fragment) {
По същия начин тук няма нужда от параметър Fragment, достатъчно е да декларираме в интерфейса Fragment this и имплементиращите ще си го имат.

2021-06-03 22:23 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
> +        default void showSendPhotoBottomSheet(SignalDetailsPresenter actionsListener,
done

2021-06-03 22:24 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
>  public interface SignalPhotoContract {
Направих нов интерфейс в същия package. Ok ли е така или на друго място да го сложа?

2021-06-03 22:24 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
> +                                              FragmentManager fragmentManager) {
done

2021-06-03 22:24 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
> +        default void openGallery(Fragment fragment) {
done

2021-06-03 22:25 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsPresenter.java
> +                FragmentTransaction fragTransaction = fragmentManager.beginTransaction();
Това не refresh-ва. Направих нов метод в view-то (защото тук вече нямаме достъп до Fragment и FragmentManager

2021-06-04 08:17 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalphoto/SignalPhotoContract.java
>  public interface SignalPhotoContract {
По-добре в отделен, за да не е объркващо.

2021-06-04 09:03 UTC, BurningAXE requested changes

2021-06-11 10:29 UTC, BurningAXE requested changes

2021-06-11 10:29 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +    private String imageFileName;
На това поле никога не му се присвоява стойност

2021-06-11 10:29 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +    public String getImageFileName() {
А този метод засечнва имплементацията от UploadPhotoContract
В резултат се праща null за filename. Странното е, че въпреки това работи :) Но все пак не е коректно :)

2021-06-11 10:29 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +    public String getImageFileName() {
Тук имаме същия казус

2021-06-15 08:55 UTC, BurningAXE approved these changes

2021-06-15 08:55 UTC, merged