48 edit signal description
HelpAPaw/Android pull request #49
Opened 2021-08-09 21:35 UTC by medeaohm

Closes #48

2021-08-10 22:35 UTC, medeaohm commented
To delete signal a new property has been created in the database. The new property is named "isDeleted", is of type integer and can assume the values 0 (if the signal is NOT deleted) or 1 (is the signal is deleted). Should we keep it in this way o maybe use a boolean property instead of int?

Currently, the change is implemented only into the staging db, we need to add it also in the database.

2021-08-24 21:55 UTC, medeaohm commented on app/src/main/res/layout/fragment_signal_details.xml
> +                            android:textIsSelectable="true"
Note: the text is not selectable when the is not enabled

2021-09-08 14:47 UTC, BurningAXE requested changes

2021-09-08 14:47 UTC, BurningAXE commented on app/src/main/res/layout/fragment_signal_details.xml
> +                                android:layout_marginLeft="-1dp"
Why is the margin negative?

2021-09-08 14:47 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +        disableScreenRotation();
Is this still needed?

2021-09-08 14:47 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +    private void closeEditSignalTitleScreen(EditText txtSignalTitle){
Maybe this method should be named endEditSignalTitleMode or something similar now.

2021-09-08 14:47 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +        enableScreenRotation();
Again - is this needed now?

2021-09-08 21:17 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +        disableScreenRotation();
It will better to keep it, otherwise, the following behaviour is observed:
1. The user presses the 'Edit' button
2. The Signal Title becomes editable
3. The user rotate the screen
4. The signal title field is not editable anymore 
5. The user need to press again the 'Edit' button to make the signal title field editable

2021-09-08 21:17 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +        enableScreenRotation();
Depending on if we decide to keep the disableScreenRotation() method.

2021-09-08 21:22 UTC, medeaohm commented on app/src/main/res/layout/fragment_signal_details.xml
> +                                android:layout_marginLeft="-1dp"
This is probably a typo. We can delete the whole row.

2021-09-08 21:23 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +    private void closeEditSignalTitleScreen(EditText txtSignalTitle){
Yes, I agree in changing the name to endEditSignalTitleMode

2021-09-09 11:41 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +        disableScreenRotation();
Actually this is a configuration problem. Fixed it in the manifest.

2021-09-09 11:41 UTC, BurningAXE approved these changes

2021-09-09 11:57 UTC, merged