List signals and notifications for user
HelpAPaw/Android pull request #57
Opened 2021-10-15 19:04 UTC by medeaohm

Closes #54 
Closes #56

2021-10-30 10:44 UTC, BurningAXE commented
Some minor UX considerations:

- [ ] I'd put the alert "Registration required" before opening "My Signals", not after
- [ ] If there are no signals in a section, it would be nice to have a message that says "You haven't submitted/commented any signals yet"
- [ ] Same for "My Notifications" screen + it makes sense to hide the "Delete" button

2021-10-30 10:48 UTC, BurningAXE commented
- [ ] Title is not fully visible on longer texts
![Screenshot (Oct 30, 2021 1_46_15 PM)](https://user-images.githubusercontent.com/5779978/139529809-ad97ecfa-bf47-4798-ac25-d38e6baa8e53.png)

2021-10-30 13:36 UTC, BurningAXE requested changes

2021-10-30 13:36 UTC, BurningAXE commented on app/src/main/res/layout/fragment_my_signals.xml
> +                    <ListView
Nesting two vertical scrolls is a bad practice. We should consider replacing the whole layout with a single ListView.
Also, we should consider replacing the ListView with RecyclerView to better handle users with a lot of signals/notifications

2021-11-01 19:16 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessSpatialSignalRepository.java
> +    @RequiresApi(api = Build.VERSION_CODES.O)
removed

2021-11-01 19:16 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessSpatialSignalRepository.java
> +    @RequiresApi(api = Build.VERSION_CODES.O)
removed

2021-11-01 19:24 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/mynotifications/MyNotificationsFragment.java
> +    private MyNotificationsContract.UserActionsListener actionsListener;
Which are the 2 references to the presenter?

2021-11-01 19:24 UTC, medeaohm commented on app/src/main/res/layout/fragment_my_signals.xml
> +                    <ListView
let's discuss this in more details

2021-11-01 19:30 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessSpatialSignalRepository.java
> +    public void getSignalsByListOfIdsExcludingCurrentUser(Set<String> signalsIds, final LoadSignalsCallback callback) {
As far as I remember, I've excluded the current user because once a user submit a signal, it will be listed in "Submitted signals". The, if the same user comment the signal, it will be listed also in the "Commented signals", hence it will be duplicated. Does this make sense?

2021-11-01 19:55 UTC, medeaohm commented
It looks like the issue with the long titles has been fixed. However, there is some empty spaces between the 2 sections "Submitted Signals" and "Commented Signals". However, given that we are going to replace the whole layout with a single RecyclerView, I am skipping this for now

2021-11-02 20:36 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +                    String notificationText = newSignalString + ": " + signal.getTitle();
should be fixed, but let's discuss if it is ok

2021-11-02 20:36 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +                            saveNotificationToDb(signal, notificationText);
should be fixed, but let's discuss if it is ok

2021-11-02 20:36 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/BackendlessPushNotificationsRepository.java
> +    private NotificationsDatabase notificationsDatabase;
should be fixed, but let's discuss if it is ok

2021-11-26 10:45 UTC, BurningAXE requested changes

2021-12-04 14:29 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/mysignals/MySubmittedSignalsPresenter.java
> +    private void getSubmittedSignalsfromDb(String ownerId) {
done

2021-12-04 14:29 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +    private void deletedSignalView() {
done

2021-12-04 14:49 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/mysignals/MySignalsContract.java
>          void onLoadMySignals();
done

2021-12-04 14:54 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/mysignals/MyCommentedSignalsFragment.java
> +        actionsListener.onLoadMySignals();
Да, няма нужда. Махам го :)

2021-12-04 15:30 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsFragment.java
> +        binding.viewSignalStatus.setVisibility(View.GONE);
По-сложно е да се направи статуса disabled, за това скрих label-a "Status" на този етап.

2021-12-05 13:32 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/mynotifications/MyNotificationsPresenter.java
> +    private NotificationsDatabase notificationsDatabase;
Готово. Може би за да сме консистентни трябва да го направим и за SignalsDatabase?

2022-01-08 22:37 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signaldetails/SignalDetailsPresenter.java
> +            signalRepository.getSignal(signal.getId(), new SignalRepository.LoadSignalsCallback() {
Ако не се лъжа беше нужно защото в другият сигнал нямахме photo url. Смених малко логиката и сега вече не се налага да го взимаме от там.

2022-01-08 22:38 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/mysignals/MySubmittedSignalsPresenter.java
> +                                    signal.setPhotoUrl(photoRepository.getSignalPhotoUrl(signal.getId()));
Направих го да се сетва направо в репозиторито. Сега трябва да е ок.

2022-01-10 10:51 UTC, BurningAXE approved these changes

2022-01-10 10:52 UTC, merged