73 change or delete user account
HelpAPaw/Android pull request #75
Opened 2022-03-05 10:39 UTC by medeaohm

Closes #73

2022-03-26 14:36 UTC, BurningAXE requested changes

2022-04-13 19:16 UTC, medeaohm commented on app/src/main/res/values/constants.xml
> +    <integer name="password_min_length">6</integer>
done

2022-04-13 19:17 UTC, medeaohm commented on app/src/main/res/values/constants.xml
> +    <integer name="password_min_length">6</integer>
done

2022-04-13 19:22 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/base/BaseActivity.java
>                      case R.id.nav_item_sign_in_out:
done

2022-04-13 19:25 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/userprofile/UserProfileFragment.java
> +    public void deleteUserProfile() {
done

2022-04-13 19:30 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/userprofile/DeleteUserProfileDialog.java
> +        dialog.setPositiveButton("Delete", (dialog1, which) -> {
done

2022-04-13 20:40 UTC, medeaohm commented on app/src/main/res/layout/fragment_user_profile.xml
> +    <RelativeLayout
removed

2022-04-13 21:31 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/data/user/UserManager.java
> +import com.backendless.BackendlessUser;
Добавих клас DisplayUser който да използваме вместо BackendlessUser-a

2022-04-13 21:58 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/userprofile/UserProfileFragment.java
> +    public void showMessage(String message) {
Преместих имплементациите на showMessage(String message) и showNoInternetMessage() в BaseFragment-a. Toва ли имаше предвид?

2022-04-16 10:44 UTC, BurningAXE approved these changes

2022-04-16 10:44 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/userprofile/UserProfileFragment.java
> +    public void showMessage(String message) {
Аз го мислих да е в отделен клас, но всъщност така е по-логично :)

2022-04-16 10:44 UTC, BurningAXE commented on app/src/main/res/values/constants.xml
> +    <integer name="password_min_length">6</integer>
Вярно...

2022-04-16 11:01 UTC, merged