Adding show nearby clinics button
HelpAPaw/Android pull request #78
Opened 2022-05-14 22:15 UTC by medeaohm

closes #77

2022-07-03 11:50 UTC, BurningAXE requested changes

2022-07-03 11:50 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/vetclinics/DownloadUrl.java
> +public class DownloadUrl {
Нещата, които са свързани с networking е добре да се изместят в data layer-a. Примерно едно VetClinicsRepository, от което да се искат клиниките за даден район и детайлите за определена клиника. А пък то вече как си ги взема да е скрито от "външния свят".

2022-07-03 11:50 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/vetclinics/VetClinicDetailsFragment.java
> +        StringBuilder vetClinicDetailsRequest =
Това е логика по-скоро за presenter-a

2022-07-03 11:50 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +//            signalsGoogleMap.clear();
Защо?

2022-07-03 11:50 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                        actionsListener.onVetClinicInfoWindowClicked(vetClinic);
Тук може би да го направим като със сигналите направо да го има самия модел на клиниката, за да не го сглобяваме на място?

2022-07-03 11:50 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +        StringBuilder vetClinicsRequest =
Това също бих го изнесъл в presenter-a.

2022-07-03 11:50 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                adapterMap.put(marker.getId(), signalInfoWindowAdapter);
Каква е ролята на adapterMap?

2022-07-03 14:28 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/vetclinics/DataParser.java
> +    public HashMap<String, String> parseDetails(String jsonData) {
Резултатите от парсването е най-добре да се опаковат в модел и така да се връщат, за да се избегне гадаене какво инфо има, правописни грешки на пропъртитата и т.н.

2022-07-05 18:37 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapPresenter.java
> +    private boolean showVetClinicsClicked = false;
done

2022-07-05 18:39 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/vetclinics/DataParser.java
> +public class DataParser {
done

2022-07-05 19:33 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/signalsmap/SignalsMapFragment.java
> +                adapterMap.put(marker.getId(), signalInfoWindowAdapter);
AdapterMap-a е нужен за Info Window-a.

2022-07-07 17:25 UTC, BurningAXE commented
- [ ] Add loading indicator while loading clinics

2022-09-21 15:30 UTC, merged