65 change language from inside the app
HelpAPaw/Android pull request #86
Opened 2022-10-01 21:56 UTC by medeaohm

Closes #65

2022-10-09 10:12 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/data/repositories/ISettingsRepository.java
> +    void saveLanguage(int languageIndex);
Does saving the language index mean if we add more languages in the future it might change the user's language?

2022-10-09 10:16 UTC, BurningAXE commented on app/build.gradle
> +    compileSdkVersion 33
- [ ] Note to self - check what other implications changing the SDK version will have on the app

2022-11-27 17:04 UTC, BurningAXE requested changes

2022-11-27 17:04 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/settings/LanguageSettingsActivity.java
> +    private int languageSelection;
А тук защо също не запазваме кода на избрания език? Така няма да се налага да ползваме конвертирането от Utils.

2022-11-27 18:49 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/settings/LanguageSettingsActivity.java
> +    private int languageSelection;
Можем да го запазим като код, дори може направо да махнем това проперти, като гледам не е особено нужно. Но няма да можем да избягаме от комвертирането защото: 

1. Тук взимаме селектираният език от адаптора, а той но го връща като индекс:
`    private void saveSelectedLanguage() {
        languageSelection = customAdapter.getCurrentLanguageSelection();

        Intent resultIntent = new Intent();
        resultIntent.putExtra(EXTRA_SELECTED_LANGUAGE, Utils.getLanguageCodeFromLanguageIndex(languageSelection));
        setResult(RESULT_OK, resultIntent);
    }`
2. Тук трябва да го пададем на адаптора, който пак очаква индекс:
`
        String languageSelectionCode = intent.getStringExtra(EXTRA_SELECTED_LANGUAGE);
        languageSelection = Utils.getLanguageIndexFromLanguageCode(languageSelectionCode);

        customAdapter = new LanguageCustomAdapter(languageListView.getContext(), languageStrings, languageSelection);
        languageListView.setAdapter(customAdapter);`

Това което ми хрумва, е че може да изнесем това конвериране в адаптера. Ще пробвам да го направя и да видим как ще изглежда

2022-11-27 19:13 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/settings/LanguageSettingsActivity.java
> +    private int languageSelection;
Да, точно това имах предвид.

2022-11-27 19:16 UTC, BurningAXE requested changes

2022-11-27 19:16 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/settings/LanguageCustomAdapter.java
>      private int currentLanguageSelection;
А тук ако също запазваме избраният код вместо индекса, ще може да се отървем от конвертирането напълно :)

2022-11-27 19:16 UTC, BurningAXE commented on app/src/main/java/org/helpapaw/helpapaw/settings/LanguageCustomAdapter.java
> +        holder.radioButton.setChecked(position == currentLanguageSelection);
И съответно тук ще сравняваме директно с кода, вместо индекса.

2023-01-02 18:02 UTC, medeaohm commented on app/src/main/java/org/helpapaw/helpapaw/utils/Utils.java
> -    public synchronized static Utils getInstance() {
Това по грешка ли е изтрито?

2023-01-14 18:09 UTC, BurningAXE approved these changes

2023-01-14 18:11 UTC, merged